public enum TokenType {

    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,


    BANG, NOT_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,


    IDENTIFIER, STRING, NUMBER,


    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
    PRINTLN, RETURN, SUPER, THIS, TRUE, VAL, VAR, WHILE,
    THROW, WHEN, DO, PACKAGE,


    EOF
}